# Makefile automatically generated by ghdl
# Version: GHDL 0.36 (tarball) [Dunoon edition] - llvm code generator
# Command used to generate this makefile:
# ghdl --gen-makefile --workdir=simu edice_test

WORKDIR=simu
GHDL=ghdl
GHDLFLAGS= --ieee=synopsys --warn-no-vital-generic --workdir=$(WORKDIR) --work=work

# Default target
all: 
	mkdir -p $(WORKDIR)
	$(GHDL) -i $(GHDLFLAGS) `find . -name "*.vhd"`
	$(GHDL) -m $(GHDLFLAGS) seq_det_fsm_tb

# Run target
run: seq_det_fsm_tb
	$(GHDL) -r seq_det_fsm_tb $(GHDLRUNFLAGS) --stop-time=1000ns --vcd=out.vcd
	open out.vcd

clean:
	rm -f $(WORKDIR)/*
